import { readFileSync } from "fs";
import { resolve } from "path";
import { sql } from "../db";
import { MUNICIPALITY } from "../../../lib/municipality-config";

// Populates city_boundary_osm — the outer-envelope fallback BarangayService
// .findBarangayForPoint() checks when a point misses every barangay polygon
// (see api/src/domain/barangay.service.ts). The table itself is created by
// drizzle/0006_city_boundary_osm.sql (migrate:city-boundary); this script
// only inserts data, and re-creates the table/index defensively (matching
// seed-dem.ts's pattern) so it also works standalone on a fresh DB.
//
// Despite the file/env-var name ("OSM boundary"), MUNICIPALITY.osmBoundaryFile
// is NOT an independent OpenStreetMap import for Porac — it's generated by
// `pnpm gis:generate-boundary` (scripts/gis/generate-porac-boundary.ts),
// which dissolves the 29 already-imported PSGC barangay polygons into one
// seamless union. That's deliberately *more* consistent for this fallback
// check than a separately-sourced OSM extract would be (no risk of the two
// datasets disagreeing at the edges) — the name is a holdover from the
// original design description in PLAN.md, where a real OSM relation was
// imported by hand. If TARGET_OSM_BOUNDARY_FILE is ever pointed at a real
// OSM extract instead, this script still works unmodified as long as the
// file is a single-feature GeoJSON FeatureCollection with a Polygon or
// MultiPolygon geometry.

type Feature = { properties: Record<string, unknown>; geometry: { type: string; coordinates: unknown } };
function ring(r: [number, number][]) { return `(${r.map(([x, y]) => `${x} ${y}`).join(", ")})`; }
function wkt(g: Feature["geometry"]) {
  const c = g.coordinates as [number, number][][][];
  if (g.type === "Polygon") return `MULTIPOLYGON((${(c as unknown as [number, number][][]).map(ring).join(", ")}))`;
  if (g.type === "MultiPolygon") return `MULTIPOLYGON(${c.map((p) => `(${p.map(ring).join(", ")})`).join(", ")})`;
  throw new Error(`Expected Polygon or MultiPolygon geometry, got ${g.type}`);
}

async function main() {
  const path = resolve(__dirname, "..", "..", "..", MUNICIPALITY.osmBoundaryFile);
  const raw = JSON.parse(readFileSync(path, "utf8")) as { features: Feature[] };
  if (raw.features.length !== 1) {
    throw new Error(`Expected exactly 1 boundary feature in ${MUNICIPALITY.osmBoundaryFile}, found ${raw.features.length}.`);
  }
  const [feature] = raw.features;
  const geomWkt = wkt(feature.geometry);
  const source = `${MUNICIPALITY.osmBoundaryFile}${feature.properties.boundary === "dissolved_barangays" ? " (dissolved from PSGC barangay polygons)" : ""}`;

  await sql.begin(async (tx) => {
    await tx`CREATE TABLE IF NOT EXISTS city_boundary_osm (
      id serial PRIMARY KEY,
      source text NOT NULL,
      geom geometry(MultiPolygon, 4326) NOT NULL,
      imported_at timestamptz NOT NULL DEFAULT now()
    )`;
    await tx`CREATE INDEX IF NOT EXISTS city_boundary_osm_geom_idx ON city_boundary_osm USING GIST (geom)`;
    // No FK ever references city_boundary_osm.id (confirmed against schema.ts
    // and every migration) — unlike barangays, a plain truncate-and-reinsert
    // is safe here and keeps this idempotent without an update-by-name dance.
    await tx`TRUNCATE city_boundary_osm RESTART IDENTITY`;
    await tx`INSERT INTO city_boundary_osm (source, geom) VALUES (${source}, ST_GeomFromText(${geomWkt}, 4326))`;
  });

  console.log(`Imported municipal boundary into city_boundary_osm (source: ${source}).`);
  await sql.end();
}

main().catch(async (e) => {
  console.error(e instanceof Error ? e.message : e);
  await sql.end();
  process.exit(1);
});
